export enum HEADERS {
    'ENTRY_NO' = 'ENTRY_NO',
    'LNAME' = 'LNAME',
    'DRVNM' = 'DRVNM',
    'PREFERRED NAME' = 'PREFERRED NAME',
    'ENTRY_CODE' = 'ENTRY_CODE',
    'LOCATION ABBR' = 'LOCATION ABBR',
    'REFERENCE' = 'REFERENCE',
    'CREATION DATE' = 'CREATION DATE',
    'BREEDING METHOD' = 'BREEDING METHOD',
    'NOTES' = 'NOTES',
    'STORAGE LOCATION ABBR' = 'STORAGE LOCATION ABBR',
    'UNITS' = 'UNITS',
    'AMOUNT' = 'AMOUNT',
    'STOCK ID' = 'STOCK ID',
    'GUID' = 'GUID'
}
