/*global angular*/
'use strict';

(function() {
	var helpModule = angular.module('help', ['ngBootbox']);

	helpModule.directive('omHelp', ['$q', '$http', '$window', '$ngBootbox', function($q, $http, $window, $ngBootbox) {
		return {
			restrict: 'E',
			scope: {
				module: '@'
			},
			template: '<span class="om-help-link bms-fa-question-circle"></span>',
			link: function(scope, element) {
				element.bind('click', function() {
					// retrieve the online help URL generated by the ff API
					$http({
						url: '/ibpworkbench/controller/help/getUrl/' + scope.module,
						method: 'GET',
						transformResponse: undefined
					}).success(function(helpUrl) {
						// if no url is retrieved/generated, we assume this is a standalone/offline install
						// the ff API calls retrieve text and html of the modal dialog for the offline help
						if (!helpUrl || !helpUrl.length) {
							var getHelpHeader = $http({
								url: '/ibpworkbench/controller/help/headerText',
								method: 'GET',
								transformResponse: undefined
							});
							var getOfflineHelpHTML = $http({
								url:'/ibpworkbench/VAADIN/themes/gcp-default/layouts/help_not_installed.html',
								method: 'GET',
								transformResponse: undefined});

							$q.all([getHelpHeader, getOfflineHelpHTML]).then(function(results) {
								$ngBootbox.customDialog({
									title: results[0].data,
									message: results[1].data,
									className: 'om-help-box',
									onEscape: true
								});
							});
						} else {
							$window.open(helpUrl);
						}
					});
				});
			}
		};
	}]);
}());
