export class UserLabelPrinting {
    constructor(
        studyId: number,
        study: string,
        fieldMapInfo: string,
        fieldMapInfoList: any,
        name: string,
        owner: string,
        description: string,
        type: string,
        date: string,
        numberOfEntries: number,
        numberOfLotsWithReservations: number,
        numberOfCopies: number,
        sorting: string,
        title: string,
        objective: string,
        numberOfInstances: number,
        totalNumberOfLabelToPrint: number,
        sizeOfLabelSheet: string,
        numberOfLabelPerRow: number,
        numberOfRowsPerPageOfLabel: number,
        barcodeNeeded: boolean,
        leftSelectedLabelFields: string,
        rightSelectedLabelFields: string,
        mainSelectedLabelFields: string,
        firstBarcodeField: string,
        secondBarcodeField: string,
        thirdBarcodeField: string,
        filename: string,
        generateType: string,
        order: string,
        filenameWithExtension: string,
        filenameDLLocation: string,
        isFieldMapsExisting: string,
        settingsName: string,
        includeColumnHeadinginNonPdf: string,
        isStockList: string,
        stockListId: string,
        stockListTypeName: string,
        inventoryDetailsList: string,
        barcodeGeneratedAutomatically: string
    ) {
    }
}
